apiVersion: v1
kind: Service
metadata:
  name: gesture-api
  labels:
    app: gesture-api
spec:
  type: NodePort
  selector:
    app: gesture-api
  ports:
    - name: http
      port: 5000
      targetPort: http
      nodePort: 30050
