name: Gesture API CI

on:
  push:
    branches:
      - main

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build image
        run: |
          docker build \
          -t draco7976/gesture-detection-api:${{ github.sha }} \
          -t draco7976/gesture-detection-api:latest .
          
          docker push draco7976/gesture-detection-api:${{ github.sha }}
          docker push draco7976/gesture-detection-api:latest

      - name: Push image
        run: |
          docker push zain7976/gesture-api:${{ github.sha }}
          docker push zain7976/gesture-api:latest