name: Gesture API CI/CD

on:
  push:
    branches:
      - main

jobs:

  test-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements-api.txt
          pip install pytest flake8

      - name: Run tests
        run: |
          pytest

      - name: Build Docker image
        run: |
          docker build -t gesture-api:test .

  deploy:

    needs: test-build
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push image
        run: |
          docker build -t zain7976/gesture-api:${{ github.sha }} .
          docker push zain7976/gesture-api:${{ github.sha }}

      - name: Configure kubectl
        run: |
          mkdir ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config

      - name: Update deployment
        run: |
          kubectl set image deployment/gesture-api \
          gesture-api=zain7976/gesture-api:${{ github.sha }}

      - name: Wait for rollout
        run: |
          kubectl rollout status deployment/gesture-api
